import { BackendStatus } from "./backend-status";

/** Placeholder for the review UI; the suggestion list, filters and actions land here next. */
export function InterlinkPlaceholder() {
  return (
    <section className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <h2 className="text-base font-medium">Review workspace</h2>
      <p className="mt-2 max-w-prose text-sm text-slate-600 dark:text-slate-400">
        Internal link suggestions are generated by the backend and reviewed here. Nothing is applied to a page
        without an explicit approval.
      </p>
      <div className="mt-4">
        <BackendStatus />
      </div>
    </section>
  );
}
