import type { Metadata } from "next";
import { Suspense } from "react";
import { InterlinkPage as InterlinkReview } from "@/features/interlink/components/interlink-page";
import { SuggestionListSkeleton } from "@/features/interlink/components/suggestion-list";

export const metadata: Metadata = {
  title: "Interlink Review | SEO Link Automation",
};

export default function InterlinkPage() {
  return (
    <main className="mx-auto flex min-h-screen w-full max-w-6xl flex-col gap-6 px-4 py-8 sm:px-6">
      <header className="flex flex-col gap-1 border-b border-slate-200 pb-4 dark:border-slate-800">
        <p className="text-xs font-medium tracking-wide text-slate-500 uppercase dark:text-slate-400">
          SEO Link Automation
        </p>
        <h1 className="text-2xl font-semibold tracking-tight text-slate-900 dark:text-slate-50">Interlink Review</h1>
        <p className="text-sm text-slate-600 dark:text-slate-400">
          Internal link suggestions generated by the backend. This view is read-only.
        </p>
      </header>
      {/* The review UI reads the URL's search params, so it renders on the client below this boundary. */}
      <Suspense fallback={<SuggestionListSkeleton />}>
        <InterlinkReview />
      </Suspense>
    </main>
  );
}
